### ISSUE TITLE
Crash after timeout

### ISSUE THREAD

**Issue by jaimeiniesta** [dequelabs/axe-core#328] opened 2017-05-09 12:04 UTC
Most of the times I try to check [this page](http://jaimeiniesta.com/articles/building-a-disqus-recent-comments-widget-with-javascript/), it crashes with:

```
$ time axe http://jaimeiniesta.com/articles/building-a-disqus-recent-comments-widget-with-javascript/ --save report.json
Running axe-core 2.2.0 in phantomjs

Testing http://jaimeiniesta.com/articles/building-a-disqus-recent-comments-widget-with-javascript/ ... please wait, this may take a minute.
Failed to inject axe-core into one of the iframes!
Error: "{\"errorMessage\":\"Timed out waiting for asyncrhonous script result after 90791 ms\",\"request\":{\"headers\":{\"Accept\":\"application/json; charset=utf-8\",\"Connection\":\"close\",\"Content-Length\":\"315\",\"Content-Type\":\"application/json;charset=UTF-8\",\"Host\":\"localhost:4444\"},\"httpVersion\":\"1.1\",\"method\":\"POST\",\"post\":\"{\\\"script\\\":\\\"return (function (context, options, config) {\\\\n\\\\t\\\\t\\\\t\\\\t/*global document, axe */\\\\n\\\\t\\\\t\\\\t\\\\tif (config !== null) {\\\\n\\\\t\\\\t\\\\t\\\\t\\\\taxe.configure(config);\\\\n\\\\t\\\\t\\\\t\\\\t}\\\\n\\\\t\\\\t\\\\t\\\\taxe.a11yCheck(context || document, options, arguments[arguments.length - 1]);\\\\n\\\\t\\\\t\\\\t}).apply(null, arguments);\\\",\\\"args\\\":[null,null,null]}\",\"url\":\"/execute_async\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"execute_async\",\"directory\":\"/\",\"path\":\"/execute_async\",\"relative\":\"/execute_async\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/execute_async\",\"queryKey\":{},\"chunks\":[\"execute_async\"]},\"urlOriginal\":\"/session/fac7c740-34ae-11e7-b035-0b552b0dcd04/execute_async\"}}"
 $s ScriptTimeoutError: {"errorMessage":"Timed out waiting for asyncrhonous script result after 90791 ms","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection":"close","Content-Length":"315","Content-Type":"application/json;charset=UTF-8","Host":"localhost:4444"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"return (function (context, options, config) {\\n\\t\\t\\t\\t/*global document, axe */\\n\\t\\t\\t\\tif (config !== null) {\\n\\t\\t\\t\\t\\taxe.configure(config);\\n\\t\\t\\t\\t}\\n\\t\\t\\t\\taxe.a11yCheck(context || document, options, arguments[arguments.length - 1]);\\n\\t\\t\\t}).apply(null, arguments);\",\"args\":[null,null,null]}","url":"/execute_async","urlParsed":{"anchor":"","query":"","file":"execute_async","directory":"/","path":"/execute_async","relative":"/execute_async","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute_async","queryKey":{},"chunks":["execute_async"]},"urlOriginal":"/session/fac7c740-34ae-11e7-b035-0b552b0dcd04/execute_async"}}
    at Object.checkLegacyResponse (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.executeScript()
    at WebDriver.schedule (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at WebDriver.executeAsyncScript (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/webdriver.js:900:17)
    at /usr/local/lib/node_modules/axe-cli/node_modules/axe-webdriverjs/lib/index.js:108:5
    at /usr/local/lib/node_modules/axe-cli/node_modules/axe-webdriverjs/lib/inject.js:63:4
    at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/promise.js:1384:14)
    at TaskQueue.execute_ (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/promise.js:3092:14)
    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/promise.js:3075:27)
    at asyncRun (/usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/promise.js:2935:27)
    at /usr/local/lib/node_modules/axe-cli/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

This happens both in my OSX machine and in a linux server (AWS Lambda).

**Comment by dylanb** [comment] 2017-05-09 15:48
@jaimeiniesta I just ran the following axe-cli command and it worked fine. Can you provide more context?

```
articles/building-a-disqus-recent-comments-widget-with-javascript/ -b chrome
Running axe-core 2.1.7 in chrome

Testing http://jaimeiniesta.com/articles/building-a-disqus-recent-comments-widget-with-javascript/ ... please wait, this may take a minute.

  Violation of "button-name" with 1 occurrences!
    Ensures buttons have discernible text. Correct invalid elements at:
     - #post > .search-wrapper > .search-form > .close-btn
    For details, see: https://dequeuniversity.com/rules/axe/2.1/button-name

  Violation of "color-contrast" with 115 occurrences!
    Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds. Correct invalid elements at:
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(1) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(1) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(1) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(2) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(2) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(2) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(3) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(3) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(3) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(3) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(3) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(4) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(4) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(4) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(4) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(4) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(5) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(5) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(5) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(6) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(6) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(6) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(6) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(6) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(7) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(7) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(7) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(8) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(8) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(8) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(8) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(8) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(9) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(9) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(9) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(9) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(9) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(10) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(10) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(10) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(11) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(11) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(11) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(11) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(11) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(12) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(12) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(12) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(12) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(12) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(13) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(13) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(13) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(13) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(13) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(14) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(14) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(14) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(14) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(14) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(15) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(15) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(15) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(15) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(15) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(16) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(16) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(16) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(16) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(16) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(17) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(17) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(17) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(17) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(17) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(18) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(18) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(18) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(18) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(18) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(19) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(19) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(19) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(19) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(19) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(20) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(20) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(20) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(20) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(20) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(21) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(21) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(21) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(21) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(21) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(22) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(22) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(22) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(22) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(22) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(23) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(23) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(23) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(23) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(23) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(24) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(24) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(24) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(24) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(24) > .post-container > .posted > a
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(25) > .post-container > .author_name > .author_name
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(25) > .post-container > .bullet
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(25) > .post-container > .timeago
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(25) > .post-container > .posted
     - #cp_embed_DhKrd,#result-iframe,#comments > li:nth-of-type(25) > .post-container > .posted > a
    For details, see: https://dequeuniversity.com/rules/axe/2.1/color-contrast

  Violation of "html-has-lang" with 1 occurrences!
    Ensures every HTML document has a lang attribute. Correct invalid elements at:
     - #cp_embed_DhKrd,#result-iframe,html
    For details, see: https://dequeuniversity.com/rules/axe/2.1/html-has-lang

  Violation of "label" with 1 occurrences!
    Ensures every form element has a label. Correct invalid elements at:
     - #post > .search-wrapper > .search-form > .search-field
    For details, see: https://dequeuniversity.com/rules/axe/2.1/label

118 Accessibility issues detected.

Please note that only 20% to 50% of all accessibility issues can automatically be detected.
Manual testing is always required. For more information see:
https://dequeuniversity.com/curriculum/courses/testing

Dylans-MacBook-Pro-2:test dylanbarrell$
```

**Comment by dylanb** [comment] 2017-05-09 15:57
My rule of thumb is: If phantomjs fails, always use Chrome or Firefox first to determine whether it is a real issue.

**Comment by jaimeiniesta** [comment] 2017-05-09 16:03
Alright, I will try then with Chrome - in fact the Chrome extension is able to analyze this page correctly.

I'm using this from the integration in Rocket Validator, running in AWS Lambda (linux server). I'm using phantomjs, but I'll try other engines.

As a default, what would you recommend using for this use case? I suspect the Chrome engine will produce better results, more similar to using the Chrome extension than phantomjs? Maybe several engines should be used as a fallback mechanism when it fails?

**Comment by jaimeiniesta** [comment] 2017-05-09 16:25
Just checked with axe-cli and the chromedriver engine for mac, it works fine but it says it can't save the results to JSON:

```
$ axe http://jaimeiniesta.com/articles/building-a-disqus-recent-comments-widget-with-javascript/ -b chrome --save report.json
Running axe-core 2.2.0 in chrome

Testing http://jaimeiniesta.com/articles/building-a-disqus-recent-comments-widget-with-javascript/ ... please wait, this may take a minute.

  Violation of "button-name" with 1 occurrences!
    Ensures buttons have discernible text. Correct invalid elements at:
     - #post > .search-wrapper > .search-form > .close-btn
    For details, see: https://dequeuniversity.com/rules/axe/2.2/button-name

  Violation of "html-has-lang" with 1 occurrences!
    Ensures every HTML document has a lang attribute. Correct invalid elements at:
     - #cp_embed_DhKrd,#result-iframe,html
    For details, see: https://dequeuniversity.com/rules/axe/2.2/html-has-lang

  Violation of "label" with 1 occurrences!
    Ensures every form element has a label. Correct invalid elements at:
     - #post > .search-wrapper > .search-form > .search-field
    For details, see: https://dequeuniversity.com/rules/axe/2.2/label

3 Accessibility issues detected.

Unable to save file!
TypeError: Converting circular structure to JSON
```

**Comment by jaimeiniesta** [comment] 2017-05-09 16:36
Regarding engine choices for running within a linux server, I think the only option is phantomjs right now? I mean, Chrome and Firefox don't run in headless mode, right?

**Comment by WilcoFiers** [comment] 2017-05-10 15:38
I'm unable to reproduce your circular dependency issue. I have no idea how that could even happen in axe. But this isn't the first time I read it.

As for linux, there are linux drivers for both Chrome and Firefox:
http://chromedriver.storage.googleapis.com/index.html?path=2.29/
https://github.com/mozilla/geckodriver/releases/

**Comment by jaimeiniesta** [comment] 2017-05-10 16:38
Thanks, I've seen the linux drivers, but I'm not sure they're headless (so
they can run in a server without a GUI).

I'll investigate this.


El may. 10, 2017 17:38, "Wilco Fiers" <notifications@github.com> escribió:

I'm unable to reproduce your circular dependency issue. I have no idea how
that could even happen in axe. But this isn't the first time I read it.

As for linux, there are linux drivers for both Chrome and Firefox:
http://chromedriver.storage.googleapis.com/index.html?path=2.29/
https://github.com/mozilla/geckodriver/releases/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dequelabs/axe-core/issues/328#issuecomment-300522437>,
or mute the thread

**Comment by jaimeiniesta** [comment] 2017-05-12 22:06
It looks like a headless Chrome is just around the corner, yay!

https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by dylanb** [comment] 2017-05-19 18:56
Looks like this was fixed in https://github.com/dequelabs/axe-core/pull/334

**Closed by dylanb** 2017-05-19 18:56 UTC
