### ISSUE TITLE
Properly-structured SVG incorrectly fails svg-img-alt

### ISSUE THREAD

**Issue by kate-hall** [dequelabs/axe-core#2587] opened 2020-10-22 18:05 UTC
Expectation: SVG with a `<title/>` child element should pass test.

Actual: Failure cites lack of a `<title/>` child element when one exists.

<pre><code>
axe-core version: 4.0.2
jest-axe: 4.0.0

- Node version: v12.16.1
- Platform:  Mac
</code></pre>

SVG element markup:
```
<svg role="img">
    <title>Accessible title</title>
    <path d="M4,2 C4,3.104 3.104,4 2,4 C0.896,4 0,3.104 0,2 C0,0.896 0.896,0 2,0 C3.104,0 4,0.896 4,2" />
</svg>
```

![axe-svg-img-alt-bug](https://user-images.githubusercontent.com/8494775/96911896-56be7f00-1456-11eb-82b6-580bc04d5fc9.png)

**Comment by straker** [comment] 2020-10-22 20:25
Interesting. I use the same html structure but I'm not seeing any errors:

```html
<svg role="img">
	<title>Accessible title</title>
	<path d="M4,2" />
</svg>
```

Any chance you could provide a link to a working example of the failure so I could take a look?

**Comment by kate-hall** [comment] 2020-10-22 21:56
Thanks for the quick response, @straker.

I spun up a basic Create React App and threw the above SVG in there (it's just a black circle, so don't expect to see much), along with the test:

https://github.com/kate-hall/test-app-axe

To reproduce, install and run the `test` script.

**Comment by straker** [comment] 2020-10-22 22:50
Alright, I dug into this and I think the issue is with the jest integration of axe. Digging into how the code interacts, axe tries to see if the [title element is visible](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/shared/svg-non-empty-title-evaluate.js#L16) but this always returns `false` with the elements jest-axe passes into axe. 

I'm not exactly sure what the solution should be as axe expects actual HTML elements and a rendered DOM, but jest uses a "fake" DOM for tests with jest.

**Comment by straker** [comment] 2020-10-23 15:22
Did some further digging. We have a [jest-react example](https://github.com/dequelabs/axe-core/tree/develop/doc/examples/jest_react) example in our codebase so I edited the `link.js` file to use a simple svg and title:

```html
<svg role="img"><title>Hello World</title></svg>
```

Doing this resulted in the violation of the title element as well. Our example uses [jsdom](https://github.com/dequelabs/axe-core/blob/develop/doc/examples/jest_react/test-helpers.js) to mount the HTML, so I also tried the same code in our [jsdom example](https://github.com/dequelabs/axe-core/tree/develop/doc/examples/jsdom) and it resulted in a violation as well.

I'll need to do some further digging into what exactly is failing with jsdom, but wanted to update you on what I found. Hopefully it's something we can get fixed in axe-core so it works better with these integrations.

**Comment by kate-hall** [comment] 2020-10-23 15:32
Really appreciate the investigation and update!

**Comment by straker** [comment] 2020-10-23 16:06
It seems the issue is with jsdom and setting the svg title node to always be `display: none`. I have filed [an issue with jsdom](https://github.com/jsdom/jsdom/issues/3064).

**Comment by straker** [comment] 2020-11-24 17:59
I'm going to close this issue. I've opened an issue with JSOM and create a [pr to fix it](https://github.com/jsdom/jsdom/pull/3076) so there's not much more we can do on our end. I even tested hiding the title with different screen readers/browsers to see if the `title` element even needed to be "visible" but it looks like it does as:

- VO/Safari reads the title
- NVDA/Firefox reads the title
- JAWS/IE11 does not read the title and even thinks the svg doesn't exist on the page (does not see it)
- JAWS/Chrome does not read the title and even thinks the svg doesn't exist on the page (does not see it)

**Closed by straker** 2020-11-24 17:59 UTC
Labels: info needed

**Comment by sevenfour** [comment] 2022-06-07 23:55
In case this is still relevant and could be useful (since the [jsdom issue #3064](https://github.com/jsdom/jsdom/issues/3064) seems to be still opened), the temporary workaround by following @straker's [PR](https://github.com/jsdom/jsdom/pull/3076) might be adding the following to the global Jest config:
```
window.document.head.insertAdjacentHTML('beforeend', `<style>svg title { display: inline; }</style>`);
```
