### ISSUE TITLE
Chrome rendering different number of results for each axe add on run for same page. The count of results are also varying on chrome add on from system to system. why is this happening?

### ISSUE THREAD

**Issue by Diana1508** [dequelabs/axe-core#2224] opened 2020-05-08 08:44 UTC
Expectation: << The axe chrome add-on should render same number of results for each run made on the same url. Also the chrome and firefox results count are not matching>>

Actual: << Chrome rendering different number of results for each axe add on run for same page/url. The count of results are also varying on chrome add-on from system to system. why is this happening?>>

Motivation: << Want to understand why there is a variation of results on different run made on chorme on different systems as well why are they different from Firefox results>>

axe-core add-on version on chrome and Firefox: 3.5.1
Chrome version system 1 and 2 -81V
Firefox version - 76

**Comment by straker** [comment] 2020-05-08 14:45
Thanks for the issue. Do you have a URL I could look at that? There are a few things that could give different number of results, such as animations hiding and showing DOM nodes, or carousels auto rotating in new items.

**Comment by Diana1508** [comment] 2020-05-13 11:52
Hi Straker,
Thanks for the responding. Here is the URL that always gives varied results for multiple runs on chrome browser same system and different systems.

https://www.abbott.com/careers.html

Regards,
Diana.

**Comment by straker** [comment] 2020-05-13 18:04
I see what you mean. However I'm not seeing this problem in 3.5.2 and am consistently getting 9 violations back with the same number of nodes in each. Are you seeing the problem in 3.5.2?

<img width="548" alt="Screen Shot 2020-05-13 at 12 02 15 PM" src="https://user-images.githubusercontent.com/2433219/81847972-a5640680-9511-11ea-9723-80aa8f6a6783.png">

**Comment by Diana1508** [comment] 2020-05-14 15:05
I raised the above issue with 3.5.1, today I tried to upgrade to 3.5.2 but, the axe core version got updated to 3.5.3. Below are the run observations done on 3.5.3
**Chrome Observations:**
1. Add-on run on same machine multiple times is rendering same count of violations, Need Reviews, Rejected but the Best Practice is varying.
2. Add-on run on different machine is rendering a huge variation of results.

**Firefox Observations:**
1. Firefox is working fine. Rendering same number of count for all kind of issues in same machine and different machine for multiple runs.

Below are the run results:

Axe Chrome add-on with core 3.5.3 version multiple run results on different machines:

**Chrome Same Machine Axe-core 3.5.3 run results**
  | Total | Violations | Need Reviews | Rejected | Best Practices
Run 1 | 161 | 10 | 18 | 0 | 133
Run 2 | **165** | 10 | 18 | 0 | **137**

**Chrome **_Different_** Machine Axe-core 3.5.3 run results**
  | Total | Violations | Need Reviews | Rejected | Best Practices
Run 1 | **209** | **55** | **31** | 0 | **123**

**Axe Firefox add-on with core 3.5.3 version multiple run results on different machines:**

**Firefox Same Machine Axe-core 3.5.3 run results**
  | Total | Violations | Need Reviews | Rejected | Best Practices
Run 1 | 157 | 10 | 18 | 0 | 129
Run 2 | 157 | 10 | 18 | 0 | 129

**Firefox Different Machine Axe-core 3.5.3 run results**
  | Total | Violations | Need Reviews | Rejected | Best Practices
Run 1 | 157 | 10 | 18 | 0 | 129

**Motivation:** << Want to understand why there is a variation of results on multiple run made on chrome on same, different systems>>

![ChromeRun_Machine2_3 5 3](https://user-images.githubusercontent.com/65013168/81950800-0975f000-9622-11ea-8d25-db28f4f6d7f5.JPG)
![ChromeRun1_Machine1_3 5 3](https://user-images.githubusercontent.com/65013168/81950806-0aa71d00-9622-11ea-8043-071c6d9d7d27.JPG)
![ChromeRun2_Machine1_3 5 3](https://user-images.githubusercontent.com/65013168/81950807-0b3fb380-9622-11ea-8281-1b094af0dd64.JPG)
![FirefoxRun_SameMachine](https://user-images.githubusercontent.com/65013168/81950808-0bd84a00-9622-11ea-9080-b5f0e09dec4f.JPG)
![FirefoxRun1_Machine1_3 5 3](https://user-images.githubusercontent.com/65013168/81950809-0c70e080-9622-11ea-9542-e2aede840656.JPG)
![FirefoxRun2_Machine1_3 5 3](https://user-images.githubusercontent.com/65013168/81950811-0c70e080-9622-11ea-9443-3b0e671593fa.JPG)

**Comment by WilcoFiers** [comment] 2020-05-18 17:14
@Diana1508 Thanks for the response.

There are two things going on here in this page:

1. the Facebook iframe is throwing off results quite a bit. The content of that iframe changes, which means different results. If you use the axe Beta scope feature you can tell axe to ignore it. That is only available in Chrome though. In the testing we've done this is the cause for all the differences except for color-contrast.

2. For some reason the color-contrast rule isn't showing any of it's results. If we run axe-core manually, the color-contrast issues are showing up, but they aren't present in the results of the Firefox extension. I can't think of a reason why that might happen, even if the rule was crashing on something that would show up in the extension. I'll get some of the extension folks involved to help debug this.

**Comment by dylanb** [comment] 2021-03-12 12:55
issue no longer occurs on that page - close? @WilcoFiers

**Comment by dylanb** [comment] 2021-09-27 18:02
Closing due to explained issue not getting any response

**Closed by dylanb** 2021-09-27 18:02 UTC
Labels: color contrast, extension
