### ISSUE TITLE
aria-sort not allowed in th

### ISSUE THREAD

**Issue by jschuler** [dequelabs/axe-core#2480] opened 2020-08-24 19:52 UTC
Hi, when i run axe-core 4.0.1 it mistakenly reports that `aria-sort` is not allowed in my `th` elements

```
{
            "any": [
              {
                "id": "aria-allowed-attr",
                "data": [
                  "aria-sort=\"ascending\""
                ],
                "relatedNodes": [
                  {
                    "html": "<th scope=\"col\" data-label=\"Name\" data-key=\"0\" aria-sort=\"ascending\" class=\"pf-c-table__sort pf-m-selected\">"
                  }
                ],
                "impact": "critical",
                "message": "ARIA attribute is not allowed: aria-sort=\"ascending\""
              }
            ],
            "all": [],
            "none": [],
            "impact": "critical",
            "html": "<th scope=\"col\" data-label=\"Name\" data-key=\"0\" aria-sort=\"ascending\" class=\"pf-c-table__sort pf-m-selected\">",
            "target": [
              ".pf-m-selected"
            ]
          },
```

I found this related issue but maybe the fix got lost over time?
https://github.com/dequelabs/axe-core/issues/283

I am not seeing the issue with `3.5.5`.

Expectation: Not report an error about using aria-sort in th

Actual: It reports that aria-sort is not allowed in the th

Motivation: Because it's a bug

<pre><code>
axe-core version: 4.0.1
Run through pupeteer 
</code></pre>

**Comment by straker** [comment] 2020-08-25 22:16
Interesting. I'm not able to reproduce with the following code snippet. Could you provide a website or code snippet that shows the error?

```js
<table>
  <tr>
    <th scope="col" data-label="Name" data-key="0" aria-sort="ascending" class="pf-c-table__sort pf-m-selected">Fo</th>
  </tr>
  <tr>
    <td>Hello</td>
  </tr>
</table>
```

**Comment by straker** [comment] 2020-09-10 15:23
Closing as without more details we cannot do anything about this. Please feel free to reopen with more details.

**Closed by straker** 2020-09-10 15:23 UTC
Labels: info needed

**Comment by malcomio** [comment] 2022-01-10 11:43
I've encountered the same issue while using axe dev-tools 4.3.5 in Edge to test a site using the PrimeVue library - the issue can be observed on their showcase page: https://www.primefaces.org/primevue/showcase/#/datatable

The relevant markup there is:

```
<th class="p-sortable-column" tabindex="0" role="cell" aria-sort="none" style="min-width: 14rem;">
```

**Comment by straker** [comment] 2022-01-10 17:24
@malcomio Thanks for the code. It looks like the issuei s that `aria-sort` on the `th` is used in conjunction to changing the role of the element `role="cell"`. It doesn't look like aria-sort [is allowed on role=cell](https://www.w3.org/TR/wai-aria-1.2/#cell) so axe looks like it is correct on reporting an error.
