### ISSUE TITLE
accessibleText API provides incorrect results for section elements

### ISSUE THREAD

**Issue by waabid** [dequelabs/axe-core#1398] opened 2019-03-02 00:09 UTC
When getting the accessible name (using accessibleText), the returned value includes the content for the section. It should not.

Example:

`<section>some section text</section>`

Expectation: should return empty accessible name

Actual: returns 

> some section text

as accessible name

Motivation: This is helpful for correctly figuring out whether a section should be considered a region landmark or not as per [ARIA 1.1 practices](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_region).

**Comment by WilcoFiers** [comment] 2019-03-07 09:37
Looked into it. I think this is caused by a less then perfect implementation of the `aria.implicitRole` method. I'm not sure why, but it doesn't seem to recognise that `section` is a landmark.

I think the way to solve this is to rewrite `implicitRole`. This method is pretty old, and it by no means reflects what the specs say it should be.

**Comment by straker** [comment] 2019-06-20 23:05
According to the spec, `section` elements are only landmarks if it has an `aria-label`, `aria-labelledby` or `title`

> The HTML5 section element defines a region landmark when it has an accessible name (e.g. aria-labelledby, aria-label or title).

Since the section is not a landmark, the accessible name correctly be the text content of the node.

**Comment by WilcoFiers** [comment] 2019-07-12 11:15
I'm going to close this issue. Using `{ strict: true }` produces the requested behaviour, the default for an axe-core run is correct.

**Closed by WilcoFiers** 2019-07-12 11:15 UTC
Labels: Support, bug, commons
