### ISSUE TITLE
Runtime issue: Axe in frame timed out: :root

### ISSUE THREAD

**Issue by synechron-sj** [dequelabs/axe-core#3542] opened 2022-07-12 18:19 UTC
<< Please describe how you encountered this issue >>

axe-core version: `4.4.2`
axe-extension version: `4.31.2`

```
Error: Axe in frame timed out: :root
    at Gr (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:99413)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:99238
```

**Comment by dylanb** [comment] 2022-07-12 18:35
@synechron-sj do you have a page where this is occurring that you can share with us?

**Comment by straker** [comment] 2022-09-14 15:27
Closing due to lack of information. Please feel free to reopen if this is still a problem, as well as please provide information on how to reproduce.

**Closed by straker** 2022-09-14 15:27 UTC
Labels: extension
