### ISSUE TITLE
Regression issue on Contrast audit using getCellFromPoint

### ISSUE THREAD

**Issue by moulinette** [dequelabs/axe-core#4155] opened 2023-09-08 15:09 UTC
### Product

axe-core

### Product Version

tested on 4.6.3 and 4.8.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

Tested using Lighthouse 10.4.0 and axe-core 4.8.0 under a linux system

test url:https://kiehls.in/

It generates an error like this:
![image](https://github.com/dequelabs/axe-core/assets/7902258/ec6bb674-5f93-43cb-8beb-8054f9eb2af0)

same issue with Lighthosue 10.1.0 and axe-core 4.6.3

Lighthouse  9.3 with  axe-core version 4.3.5 was not having this error

Test reports attached
[test reports (2).zip](https://github.com/dequelabs/axe-core/files/12561196/test.reports.2.zip)

**Comment by straker** [comment] 2023-09-08 17:25
Thanks for the issue. I'll take a closer look at this next week.

**Comment by straker** [comment] 2023-09-12 14:05
So I tried to test the page but am unable to reproduce the error. Axe-core v4.8.0, axe extension  using axe-core v4.7.2, and lighthouse all return fine without errors.

<img width="1704" alt="screen shot of running lighthouse on kiehls.in showing a run without axe-core erroring on color-contrast" src="https://github.com/dequelabs/axe-core/assets/2433219/3f2997b0-25f1-4e22-aa48-6b0e45b64c6f">

<img width="637" alt="screen shot of the color-contrast results from the lighthouse run showing no axe-core errors" src="https://github.com/dequelabs/axe-core/assets/2433219/828c44b5-b3f8-4d50-bd76-6f78df91bc2b">

**Comment by straker** [comment] 2023-09-12 14:07
I'll note that I was using a mac to test this. I don't have a Linux system to try the same thing but I'll see if I can find someone who does.

**Comment by moulinette** [comment] 2023-09-13 12:51
Thanks @michael-siek 
It is also working fine on windows

I'm still having the issue on my test machine with chromium 115 and alpine:3.18.3

I'll do a try using another another linux distrib and let you know

**Comment by straker** [comment] 2023-09-14 13:54
Interesting. I'll try using Lighthouse CLI and see if the same issue comes up.

**Comment by straker** [comment] 2023-09-14 14:27
Confirmed it's a problem in the Lighthouse CLI. Lighthouse CLI v11.1.0 is [using axe-core 4.8.1](https://github.com/GoogleChrome/lighthouse/releases/tag/v11.1.0) and the color-contrast rule errors with `Cannot read properties of undefined (reading 'getCellFromPoint')`. The error occurs in both headless and headed mode.

Looking at the headed run, Lighthouse is testing the page in mobile view. When I use the Toggle Device view in DevTools to enter mobile view and run axe-core directly, I then get the error about `getCellFromPoint`, so it looks like it only occurs in the mobile view of the page.  

Looking at the issue, it looks like there is a mobile menu whose container is offscreen `#menu-top16947011201434579698-menu` which contains a close button which is not offscreen `<span>X<span>`. When axe runs color-contrast on the close button, it tries to [navigate up the elements container](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/dom/get-rect-stack.js#L28-L34). The container element does not have a `grid` since it was offscreen so that is why the error occurs.

**Comment by ittaibaratz** [comment] 2023-09-22 19:15
We are running into the same issue with a similar setup: Lighthouse 11.1.0 / axe-core 4.8.1 / Headless Chrome:

![image](https://github.com/dequelabs/axe-core/assets/1454683/fe680708-b66e-41a1-8f1b-3de5d17e1f86)

The app is behind authentication but I see the issue is reproduced already.

**Comment by moulinette** [comment] 2024-05-26 07:33
Hi,
To inform you that this issue was fixed on my side by using the "axe-core": "4.9.0" version
Thanks for your help

**Comment by straker** [comment] 2024-05-28 19:44
Thanks for letting us know. I'll go ahead and close this ticket.

**Closed by straker** 2024-05-28 19:44 UTC
Labels: fix, color contrast
