### ISSUE TITLE
user-scalable="no" is ignored by iphone 

### ISSUE THREAD

**Issue by goodwitch** [dequelabs/axe-core#1276] opened 2018-12-12 21:31 UTC
Using the latest axe extension on this page: 
https://online.citi.com/US/JRS/portal/template.do?ID=Accessibility&JFP_TOKEN=UXJMV33F

I get the following error: 

> Zooming and scaling must not be disabled"
> Ensures <meta name="viewport"> does not disable text scaling and zooming"
> To solve this violation, you need to:
> Fix the following:
> user-scalable=no on <meta> tag disables zooming on mobile devices"

**Expectation:**  When I tested to see if "pinch-to-zoom" was actually disabled, by pulling out an iPhone running iOS 12.0 and opening the page above in Safari...I expected pinch-to-zoom to be disabled.

**Actual:**  When I tested this on an iPhone running iOS 12.0...I was  surprised that I was ABLE to pinch-to-zoom.   See article "[How to disable viewport scaling in iOS 10? You don't"](https://wouterdeschuyter.be/blog/how-to-disable-viewport-scaling-in-ios-10-you-dont)

I then asked my team to test it on Android Devices and got the following results:

- Galaxy S7 Edge - Chrome Browser - pinch-to-zoom worked.  zooming was NOT DISABLED
- Galaxy S7 Edge - Firefox Browser - pinch-to-zoom disabled 
- Pixel 2 XL - Chrome Browser - pinch-to-zoom disabled

**Motivation:** I think it would be super helpful to add some details that would clue a person in to not just test on mobile...but to test on Android in multiple browsers.  Without this additional detail, I'm afraid people will think this is a false positive. 

I'd love to see this detail added in the axe extension interface itself.  Maybe change:
> Fix the following:
> user-scalable=no on <meta> tag disables zooming on mobile devices"

to

> Fix the following:
> user-scalable=no on <meta> tag disables zooming on some mobile devices. check on android in multiple browsers."

axe-core version: 3.1.1
axe-devtools: 3.6.0
browser:  Chrome 70 (on Mac laptop OS Sierra 10.12.6)

**Comment by jkodu** [comment] 2019-07-23 11:40
@goodwitch I went through the [site](https://online.citi.com/US/JRS/portal/template.do?ID=Accessibility&JFP_TOKEN=UXJMV33F) in question & this does not flag this violation any more.

Also I tested on some iOS and Andriod devices & zooming was not disabled.

Could you help test another time on your end? This may help us close this issue, with the only change being a better message for the rule.

**Comment by goodwitch** [comment] 2019-07-23 18:14
@jkodu I think that is because the site has changed (citi removed the user-scalable part).  I went back in time (using the wayback machine) and found a version of the page the has user-scalable defined...and ran axe on it..and axe still calls it a failure.  Try testing the page as it looked on Dec 1.  https://web.archive.org/web/20181201191942/https://online.citi.com/US/JRS/portal/template.do?ID=Accessibility  (okay, so it is a non-english version of the page...but...shrug...it has that user-scalable piece).   So...I think this is still a problem.  Because...it is not an automatic failure...(except maybe on iOS at this moment).

**Comment by goodwitch** [comment] 2019-07-23 18:23
Oh...and I just took the time to open this URL on my iPhone (iOS 12.3.1) and was able to pinch-to-zoom with no problem (even though the page has a user-scalable="no") 

<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">

https://web.archive.org/web/20181201191942/https://online.citi.com/US/JRS/portal/template.do?ID=Accessibility

**Comment by straker** [comment] 2019-11-25 17:16
Investigate if related to #694

**Comment by straker** [comment] 2019-12-23 23:10
Duplicate of #694 in terms of resolution

**Closed by straker** 2019-12-23 23:10 UTC
Labels: rule metadata
