### ISSUE TITLE
Label has &nbsp as its only text is passing.

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#1019] opened 2018-07-23 18:25 UTC
AXE 3.0 is currently not flagging this failure. (in latest Chrome on Windows)

```
<span>the real label</span>
<label for="p1">&nbsp</label>
<input ... id="p1">
```

**Comment by WilcoFiers** [comment] 2018-07-23 19:14
Ha! Good catch. Thanks David!

**Comment by WilcoFiers** [comment] 2018-07-25 01:00
Hey @DavidMacDonald I ran the example locally and it's coming up as a failure. Can you provide me with some way to reproduce the issue?

**Comment by WilcoFiers** [comment] 2018-08-05 15:07
Closing the issue as I was unable to reproduce it.

**Closed by WilcoFiers** 2018-08-05 15:07 UTC
