### ISSUE TITLE
Running axe analyze on an overlay, the issues reported should be limited to overlay

### ISSUE THREAD

**Issue by poojap1** [dequelabs/axe-core#807] opened 2018-03-27 23:13 UTC
For ex: This is the base page -
https://www.starbucks.com/store-locator?map=47.58219,-122.334906,15z
Run analyze and you will see 3 violations being returned.
Now when you click on the 'Filter' button towards right near the search icon, an overlay opens up with filter options.
When i run axe analyze on the overlay, i get 2 violations and 155 Needs review.
It flags color contrast now for the base page due to the overlay. Also the violations are from the base page. The overlay doesn't seem to have any violations.

Axe-core is not limiting the accessibility check on the overlay only. The background now has Aria-hidden=true when overlay is active.
Axe should run analyze on the overlay only.

**Comment by WilcoFiers** [comment] 2018-03-28 16:53
I think aria-hidden element shouldn't be ignored for color contrast, although it's probably better to treat them as review items. As for obscured elements... I'm not sure why we wouldn't just pass those for color contrast. @marcysutton I tried to dig up what motivation we had for this, but I can't find much. Do you recall what the main reason for that was, if any? It certainly could have been an oversight on our part.

**Comment by WilcoFiers** [comment] 2018-03-30 10:04
The question I'm mainly interested in with this one is if we should pass elements that are entirely obscured, instead of putting it in needs review. WDYT?

**Comment by dylanb** [comment] 2018-04-01 19:22
The correct way to do this is to set the `inert` attribute on the aria-hidden section. In that scenario, we should ignore it for color contrast purposes.

**Comment by WilcoFiers** [comment] 2019-04-24 16:52
This issue is a duplicate of #1459. I'm going to close it, as 1459 has more current.

**Closed by WilcoFiers** 2019-04-24 16:52 UTC
Labels: bug, rules
