### ISSUE TITLE
It says "An error occured." 

### ISSUE THREAD

**Issue by teccean** [dequelabs/axe-core#1806] opened 2019-09-10 12:31 UTC
That's it. I push the "Analyze" button and then that's all it says.

See the below screen shot.
![MinimalaXeError](https://user-images.githubusercontent.com/22302476/64613924-490a7f00-d3a5-11e9-9644-f2a13f25be05.png)

**Comment by WilcoFiers** [comment] 2019-09-10 13:27
What page did you see this issue on? If you click the "Error details" button, what error do you see?

**Comment by Zacros7164** [comment] 2019-09-10 14:40
I am getting the same error. Here are the error details.

Error: Could not establish connection. Receiving end does not exist.

**Comment by straker** [comment] 2019-09-10 15:37
We had someone open a similar issue a bit ago #1769. Have you tried restarting the chrome browser? There's also a new permission agreement you need to accept in order to run the latest version of axe.

**Comment by scurker** [comment] 2019-09-10 17:27
There was a [recent change with Chrome 72](https://support.google.com/chrome_webstore/answer/2664769) that changes how the extension accesses the current active tab. If you don't have _On All Sites_ selected for the _Site Access_ permission, you will need to first click on the extension in Chrome's navbar to allow it to access the current tab.

If you are sure this isn't your issue, we need a few more details:

* Can you reproduce this on multiple sites or just a single site?
* What version of Chrome are you using?
* What version of Axe is installed?

**Comment by kshukla06** [comment] 2019-09-10 18:13
I am getting the same error. :(

**Comment by Zacros7164** [comment] 2019-09-11 17:05
I had just installed the extension yesterday, but I hadn't restarted the browser, that fixed it for me.

**Comment by sudPatil** [comment] 2019-09-19 10:36
Facing same issue
**Chrome** : Version 77.0.3865.75 (Official Build) (64-bit)
Below is the screenshot : 

![image](https://user-images.githubusercontent.com/32299249/65236922-360b5380-daf7-11e9-8967-6ff6b44f0d9b.png)

**Comment by sudPatil** [comment] 2019-09-19 12:57
I faced same issue. 
When i changed some setting in axe plug-in I am able to run tool.
Can you check the plug in setting it should be  **On all sites** as shown below

![image](https://user-images.githubusercontent.com/32299249/65245848-f8182a80-db0a-11e9-9b58-076a07045e5c.png)

**Comment by straker** [comment] 2019-10-11 16:31
Closed as this seems to be resolved by restarting the browser or the extension permissions.

**Closed by straker** 2019-10-11 16:31 UTC
Labels: needs discussion
