### ISSUE TITLE
Buttons with proper role not detected as having button role

### ISSUE THREAD

**Issue by frank6tg** [dequelabs/axe-core#2748] opened 2021-01-13 14:37 UTC
In the guided test for buttons (axe core 4.1.1 / beta v4.6.2) axe is reporting buttons as not having a role. The website uses Beaver Builder Plugin (WordPress)

Temporary URL: https://26d0d0c7af.nxcli.net/ (future URL will be BenBrownInsurance.com)

The location on the site is:
`body.home.page-template-default.page.page-id-2.fl-builder.fl-theme-builder-header.fl-theme-builder-footer.fl-theme-builder-part.fl-framework-base.fl-preset-default.fl-full-width.fl-search-active.fl-builder-breakpoint-large` > div.fl-page:nth-of-type(1) > div#fl-main-content.fl-page-content:nth-of-type(2) > div.fl-content-full.container:nth-of-type(1) > div.row:nth-of-type(1) > div.fl-content.col-md-12:nth-of-type(1) > article#fl-post-2.fl-post.post-2.page.type-page.status-publish.hentry:nth-of-type(1) > div.fl-post-content.clearfix:nth-of-type(1) > div.fl-builder-content.fl-builder-content-2.fl-builder-content-primary.fl-builder-global-templates-locked:nth-of-type(1) > div.fl-row.fl-row-full-width.fl-row-bg-color.fl-node-5ff511ed6a846:nth-of-type(3) > div.fl-row-content-wrap:nth-of-type(1) > div.fl-row-content.fl-row-fixed-width.fl-node-content:nth-of-type(1) > div.fl-col-group.fl-node-5ff50f2aeff1c.fl-col-group-equal-height.fl-col-group-align-center:nth-of-type(1) > div.fl-col.fl-node-5ff50f2aeff1f.fl-col-small.fl-col-small-full-width:nth-of-type(2) > div.fl-col-content.fl-node-content:nth-of-type(1) > div.fl-module.fl-module-button.fl-node-5ff50f2aeff21:nth-of-type(1) > div.fl-module-content.fl-node-content:nth-of-type(1) > div.fl-button-wrap.fl-button-width-auto.fl-button-center:nth-of-type(1) > a.fl-button:nth-of-type(1)`

The html clearly shows the role of "button"

`**<a href="https://26d0d0c7af.nxcli.net/contact-us/" target="_self" class="fl-button" role="button">**
							<span class="fl-button-text">Contact Us Today</span>
					</a>`

**Comment by erik-deque** [comment] 2021-01-13 20:13
Closing as this is a duplicate of #2747

**Closed by erik-deque** 2021-01-13 20:13 UTC
Labels: extension
