### ISSUE TITLE
Axe does not analyze after ckick to "Analyze" button

### ISSUE THREAD

**Issue by MarioBatusic** [dequelabs/axe-core#1728] opened 2019-07-29 08:35 UTC
Expectation: << Describe what you expect the product to do >>
Axe should start analyzing after activating the "Analkyze" button.
Actual: << Describe what the product actually does >>
The program does nothing. An error message occurs.
Detailed Error description given by Firefox:
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77415
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77103
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77747
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77103
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77747
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77103
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77747
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77103
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77747
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77103
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77747
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77103
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77747
j@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:60073
u/<@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:69:170372
u@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:69:170344
t.default/<@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:69:172614

<pre><code>
axe-core version: 3.8.0
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions
Firefox with NVDA.
For Tooling issues:
- Node version: XX  
- Platform:  Windows
</code></pre>

**Comment by WilcoFiers** [comment] 2019-07-29 16:31
This seems to be a duplicate of #1512. We are working on it. I'm closing this one. If it is a different issue, feel free to reopen.

**Closed by WilcoFiers** 2019-07-29 16:31 UTC
