### ISSUE TITLE
autocomplete-valid should be 'failure or needs review' rather than 'failure' and algorithm needs refinement

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-core#2411] opened 2020-07-22 23:25 UTC
Expectation: 
Something like the following:
* Failure only occurs for inappropriate input field type when autocomplete value is in Input Purposes for User Interface Components.
* All other usages of autocomplete should be marked "needs review":
    * If appropriate field type and in Input Purposes, user needs to verify the accessible name of the field aligns with the field implied by the autocomplete value. If it aligns, pass. If it does not align, fail. 
    * If autocomplete value is unrecognized, user needs to verify the accessible name of the field is not within the range of identifiers in Input Purposes. If so, pass.
* All fields of appropriate type (select, input, textarea) that do not use the autocomplete attribute should be marked "needs review," and the user should be instructed to manually verify that the accessible name of the field is not in Input Purposes or, if it is in Input Purposes, that some other mechanism is being used to programmatically identify the purpose of the field.

Actual: 
autocomplete-valid *returns 'failure'* whenever autocomplete value on select, input (of appropriate type), or textarea is not in Input Purposes for User Interface Components. Instructions say that the incomplete value(s) are inappropriate or incorrectly formatted.

Motivation: 
WCAG 1.3.5 Identify Input Purpose would only be failed if the field's type and *accessible name* did not align with the autocomplete value, as outlined scoped in Input Purposes. 

But this rule does not/cannot test appropriate alignment between a field's accessible name and its autocomplete value. It appears only to test if the autocomplete value is on an appropriate type of field and is a value specified in the list of Input Purposes for User Interface Components list.

For example: 
`<label for="horse">Your horse's birthday</label> <input id="horse" autocomplete="given-name">`
is a failure of 1.3.5, because the name is not appropriate to the field's purpose, But this passes autocomplete-valid.
And 
`<label for="horse">Your horse's birthday</label> <input id="horse" autocomplete="horse-name">`
is a pass of 1.3.5, because the name is not within the scope of Input Purposes. But this would fail autocomplete-valid.

Manual review is needed if the autocomplete-value rule returns a potential problem, and, likewise, a pass of autocomplete-valid does not mean 1.3.5 is passed.

Resources:
[Failure of Success Criterion 1.3.5 due to incorrect autocomplete attribute values](https://www.w3.org/WAI/WCAG21/Techniques/failures/F107)

**Comment by WilcoFiers** [comment] 2020-07-23 12:54
Hey Ken. Thanks for the feedback. Do you have an example of something like that existing on a real website?

I know that in theory someone could make up their own autocomplete value, similarly someone could make up their own roles and aria attributes. In practice people don't do this. Or at least, nothing like that has ever been reported. If you've found a website that has `autocomplete="horse-name"` on an input element, I'd definitely love to see it.

**Comment by kensgists** [comment] 2020-07-27 14:41
Hi Wilco, No. I was just making something up for purposes of illustration.

While "horse-name" would be flagged as either a warning or a violation in an HTML validator, I don't believe it could be considered a WCAG violation, unless paired with a label that aligned with a purpose from the Input Purposes list. (Maybe 4.1.1 Parsing, but even that is pretty constrained in purpose.)

The general point is that, while axe can do a lot in the cases where the developer is trying to get it right but messes up -- checking order of values, correctness, and appropriateness of values for field certain field types, etc. -- it can only truly "fail" in limited cases. 

I would agree we likely have a fail if the field type is not appropriate to the purpose and the purpose comes from the Input Purposes list.  It would mean that it would be impossible to "pass" 1.3.5, even with an appropriate label for the field.

But in other cases I think the rule is a "needs review." Using the algorithm as currently implemented, false negatives/misses are easy to achieve:
`<label for="name1">Name:</label>
<input type="text" name="field1a" autocomplete="email" id="name1">`
is a pass of autocomplete-valid but is a fail of 1.3.5, coming directly from a failure example in F107.

**Comment by WilcoFiers** [comment] 2020-07-30 10:23
So the underlying assumption for a lot of what axe-core (and every other accessibility tool) does is that developers don't just make stuff up. There is no real reason why someone might just invent a new role, aria attribute, or autocomplete value. In theory it obviously could happen, but in practice, I've never seen it.

There's a tradeoff in this. Do you stop reporting very obvious accessibility issues, such as mistyping autocomplete values, for a theoretical possibility of a false positive?

The answer for axe-core is that it is OK to make assumptions about the way elements and attributes will be used. Because we have a no false positives policy, if someone finds a false positive caused by any of those assumptions, we are committed to fix it. We've been wrong about some of our assumptions in the past, and we've fixed them. But it is real-world false positives that drives the decision to downgrade violations to needs review.


I don't think this is something we are going to change the default of this. If you'd like to have this behave different in the way you use axe-core, you can use custom rules to address this. In axe-core 4.0 we're releasing a new option which allows you to ensure a rule always marks [things for review](https://github.com/dequelabs/axe-core/issues/2186#issuecomment-630416033). You'd have to split the rule up into two, but this is fairly straight-forward to do.

I'm going to close the issue, as without a real-world example of a false positive, I don't think there is anything to change here.

**Closed by WilcoFiers** 2020-07-30 10:23 UTC
Labels: info needed

**Comment by kensgists** [comment] 2020-07-30 13:42
I'm definitely not saying, "Do you stop reporting very obvious accessibility issues, such as mistyping autocomplete values, for a theoretical possibility of a false positive?"

But is it prudent to flag something a "pass" rather than a "needs review" when it is trivially easy to fail the SC and still have the attribute value be correct?

My last example points to an instance where axe would pass something that is failure of the SC. 

This is a false negative rather than a false positive, and I know the promise is no false positives. Making the rule "failure, needs review" rather than "failure" is what I am suggesting. 

You have definite failure conditions in the rule as implemented,  but __all__ "passes" are really "needs review" rather than a green light. A developer could very easily and without malicious intent or lack of competence mark a field labelled as "child's birthday" with automcomplete=bday. That would pass axe but fail the SC.

**Comment by straker** [comment] 2020-07-30 14:26
Unfortunately detecting intent between a label and autocomplete value is not something automated tools can test (only 50% of accessibility errors can be automatically tested). So yes, even though a user could label an input with a misleading value while the autocomplete says something different is a problem, detecting that would fall under the realm of manual testing.

**Comment by kensgists** [comment] 2020-08-03 03:09
Right, "manual review" rather than fail, in all cases other than those where type mismatch or value order errors are detected -- those seem like a definitive fail.

**Comment by CurtisKimball** [comment] 2021-05-05 17:08
I'm looking into this flag on one of our pages now and it seems to be flagging a postal-code field because it has the input type of "tel" in stead of "text".
I need to be able to explain what the impact of this mismatch actually is for the user.
