### ISSUE TITLE
Error in extension with axe-coconut

### ISSUE THREAD

**Issue by jnurthen** [dequelabs/axe-core#602] opened 2017-11-03 23:55 UTC
Running the following page in axe-coconut I get an error in the extension.
http://jdevadf.oracle.com/adf-richclient-demo/faces/components/table.jspx

The error is 
coconut.bundle.js:4400 undefined
(anonymous) @ coconut.bundle.js:4400

coconut.bundle.js:4401 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at coconut.bundle.js:4401
    at <anonymous>

Initially I thought this was only in chrome canary but I now see I get errors when running in both production Chrome and Chrome Canary.

**Comment by WilcoFiers** [comment] 2017-11-05 05:35
Yep, that looks like it's on our side. Thanks for the report! We're on it.

**Comment by marcysutton** [comment] 2018-01-23 16:22
Hey @jnurthen, can you check the URL for the above page? I'm getting the message "No Response from Application Web Server"

**Comment by jnurthen** [comment] 2018-01-23 16:36
@marcysutton it is the correct URL but the page is down at the moment. I'll see if I can contact someone to get it bounced.

**Comment by WilcoFiers** [comment] 2018-02-26 13:12
@jnurthen The page is still not available. Do you have an alternative way to reproduce the issue?

**Comment by marcysutton** [comment] 2018-03-13 18:13
Without a way to reproduce this, we can't take action. I'm going to close this one, but feel free to reopen if you've got a page that triggers the error.

**Closed by marcysutton** 2018-03-13 18:13 UTC
