### ISSUE TITLE
link-name: Image link accessible name not recognised

### ISSUE THREAD

**Issue by Brynman** [dequelabs/axe-core#2783] opened 2021-01-28 12:24 UTC
All of the product images on this page https://www.habitat.co.uk/browse/storage/bookcases-and-shelving/c:809337/ have alt texts that serve as the accessible name for each image link. Chrome picks this up but the axe link-name check doesn't.
![image](https://user-images.githubusercontent.com/60389544/106137750-0d6f8100-6163-11eb-8135-be89bd452ba9.png)
![image](https://user-images.githubusercontent.com/60389544/106137817-2aa44f80-6163-11eb-8f9e-b4fadbdb6ba1.png)

I see these as false positives.

Expectation: << Not flag the image links with accessible names >>

Actual: << image links with accessible names are being flagged >>

Motivation: << I have incorrectly reported an issue to a product team and senior management  based on a spike in issues that I believe are false positives - lack of trust in the tooling can be extremely damaging >>

<pre><code>
axe-core version: 4.1.1
axe-webdriver, extension  4.7.1

</code></pre>

**Comment by straker** [comment] 2021-01-28 16:22
Ho boy that was a hard bug to track down. So the problem is that the links don't have names, but that any of those products don't have the image when they are offscreen. As soon as the image is in view the div surrounding the `<picture>` element is put in. Thus all off-screen links do not have names.

![image](https://user-images.githubusercontent.com/2433219/106167309-4bac7680-614a-11eb-876d-19b0a60bbdb2.png)

**Comment by Brynman** [comment] 2021-01-28 16:43
Ha! nice one @straker . Good detective work. I just verified this by running the extension twice, once on page load and then once after I had scrolled down the page.

**Comment by straker** [comment] 2021-01-28 17:34
Awesome. I'm going to close this then.

**Closed by straker** 2021-01-28 17:34 UTC
