### ISSUE TITLE
axe ignores transparent content model?

### ISSUE THREAD

**Issue by yinonov** [dequelabs/axe-core#3077] opened 2021-07-13 11:42 UTC
Axe test fails with “Headings must not be empty” on the following
```html
<h1><my-element>Lorem ipsum dolor sit amet</my-element></h1>
```
I figure, [transparent content model](https://html.spec.whatwg.org/multipage/dom.html#transparent-content-models) should just propagated the textNode as content for the h1.

Furthermore, the following snippet **pass**
```html
<h1>
  <button>
    <span>
      Personal Information
    </span>
  </button>
</h1>
```
is this fail a valid?
is there anything should be done to make the custom element an explicit transparent content?
the shadow tree of the custom element contains only a `slot` element
Product: chai-a11y-axe (axe-core)

**Comment by straker** [comment] 2021-07-13 15:49
I tested this as-is in Safari, and with an unregistered custom element it doesn't produce the failure. Are you registering the custom element? And if so, what does that code look like?

**Comment by yinonov** [comment] 2021-07-13 18:47
well that's very odd. test now magically pass. with same code. I had chrome and safari running side by side and safari repeatedly failed. i'll close now and reopen if will reproduce. 🙏

**Comment by yinonov** [comment] 2021-07-13 19:07
ok yeap it's back. debugged and found out the problem occurs on lit based classes
```js
export class MyElement extends LitElement {}
```
in oppsed to 
```js
export class MyElement extends HTMLElement {}
```
which passes just fine

should this be reference any [lit](/lit/lit) issue?

**Comment by straker** [comment] 2021-07-13 19:17
Can you post the full code that reproduces the error? I can see if it's more a lit issue or an axe-core issue.

**Comment by yinonov** [comment] 2021-07-13 19:26
sure, it's a simple karma & chai testing environment where I simply test if the html is accessible.
there are some inner helper fns so if need a reproduction link, i'll add 1.
if you actually can't reproduce the problem by simply testing against Lit based class, it should raise a flag for me. but I never faced such issues with the testing environment nor these helper fns...
```js
it('should have 0 accessibility violations when nested in semantic tag', async () => {
  const [actualElement] = addElement(
    textToDomToParent(`<h1><my-element>Lorem ipsum dolor sit amet</my-element></h1>`)
  );
  await actualElement.updateComplete;

  await expect(actualElement).shadowDom.to.be.accessible();
});
```

**Comment by straker** [comment] 2021-07-13 19:29
Sorry meant the code to the my-element (the full class extension, etc.). Without that I can't see what's happening on my end.

**Comment by yinonov** [comment] 2021-07-13 19:47
> ok yeap it's back. debugged and found out the problem occurs on lit based classes
> 
> ```js
> export class MyElement extends LitElement {}
> ```
> 
> in oppsed to
> 
> ```js
> export class MyElement extends HTMLElement {}
> ```
> 
> which passes just fine
> 
> should this be referenced to any [lit](/lit/lit) issue?

this was enough to reproduce. I just did

**Comment by straker** [comment] 2021-07-13 19:56
Oh, just extending the class hu? Interesting. I'll take a look

**Comment by yinonov** [comment] 2021-07-13 20:00
in more detail
```js
import { LitElement } from 'lit-element';

export class MyElement extends LitElement {}
customElements.define('my-element', MyElement);
```
and [the above test](https://github.com/dequelabs/axe-core/issues/3077#issuecomment-879342441)

**Comment by straker** [comment] 2021-07-13 20:14
Ok. So the issue is with your class definition and a slight issue of a race condition. The first issue is that your custom element doesn't define a `render` function and so has no content (a shadow element will remove all children from it, so the text you have in the HTML is not there once the component is registered with shadow).

The race condition is that in Chrome the element isn't fully registered until after a short delay, so when you run your test the text still exists. If you put a delay on your test you'll start to see a consistent failure in all browsers. Safari doesn't seem to have the delay.

I'm going to close this as it's not an issue with axe-core.

**Closed by straker** 2021-07-13 20:14 UTC

**Comment by yinonov** [comment] 2021-07-13 20:25
I over cleaned it for the sake of the reproduction here, so the render was there to begin with 😬
Anyway **you're right** about the race condition, it occurred on chrome as well.
Thanks for taking the time to verify 🙏
