### ISSUE TITLE
Issue with background color

### ISSUE THREAD

**Issue by awebdeveloper** [dequelabs/axe-core#311] opened 2017-04-26 06:15 UTC
This complained that both background and foreground were white which clearly is not the case.

Both the elements were missing a background property hence i guess it complained but it's wrong.

I fixed it by specifying a background colour 

<img width="561" alt="screen shot 2017-04-26 at 11 39 29 am" src="https://cloud.githubusercontent.com/assets/1593429/25420321/3d2b0686-2a75-11e7-90eb-de909210e404.png">

**Comment by marcysutton** [comment] 2017-04-26 15:20
Pretty sure this is a duplicate of https://github.com/dequelabs/axe-core/issues/299, so I'm going to close this. Keep an eye on that issue instead. Thanks!

**Closed by marcysutton** 2017-04-26 15:20 UTC

**Comment by marcysutton** [comment] 2017-04-27 15:52
We released axe-core 2.2.0 yesterday, you can check to see if your issue persists.

**Comment by awebdeveloper** [comment] 2017-04-27 16:14
the chrome extension is still at 2.1.7 

Let me try this from terminal
