### ISSUE TITLE
axe-coconut in Chrome appears to be broken

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-core#1533] opened 2019-05-01 14:58 UTC
coconut appears to be broken. Any page I test gives:

TypeError: Cannot read property 'nodeMap' of undefined
    at G (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:74309)
    at Object.utils.getFlattenedTree (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:81423)
    at Object.j [as cleanup] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:51377)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321777
    at new Promise (<anonymous>)
    at Object.u [as highlight] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321749)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:85:171163
    at onMessage (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/browser-polyfill.js:1056:22)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)

Tested today, May 1, 2019, with Chrome version 71.0.3578.98

**Comment by scurker** [comment] 2019-05-01 17:08
Hi @kensgists, thanks for filing an issue. This looks like it's a duplicate of #1532 so if you have any additional info, be sure to follow the thread there.

**Closed by scurker** 2019-05-01 17:08 UTC
