### ISSUE TITLE
Runtime issue: Respondable target must be a frame in the current window

### ISSUE THREAD

**Issue by Anthony-YY** [dequelabs/axe-core#2853] opened 2021-03-30 06:18 UTC
<< Please describe how you encountered this issue >>

axe-core version: `4.1.3`
axe-extension version: `4.8.6`

```
Error: Respondable target must be a frame in the current window
    at rr (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:95394)
    at ar (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:95649)
    at ur (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:96233)
    at cr (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:98031)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:99806
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:92014
    at Object.defer (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:92048)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:99772
    at Array.forEach (<anonymous>)
    at mr (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:99630)
```

**Comment by WilcoFiers** [comment] 2021-03-30 13:13
@Anthony-YY Can you share the page you are seeing this issue on?

**Comment by dylanb** [comment] 2021-03-30 15:14
@Anthony-YY If you cannot share the page, can you confirm that it is a page with shadow DOM that has an iframe in it?

**Comment by WilcoFiers** [comment] 2021-03-31 13:28
If so, this is a duplicate of #2835

**Comment by dylanb** [comment] 2021-04-05 19:01
@wilco close?

**Comment by straker** [comment] 2021-06-17 20:23
Going to close as a duplicate of #2835 since no additional information was provided.

**Closed by straker** 2021-06-17 20:23 UTC
Labels: info needed
