### ISSUE TITLE
Incorrectly reporting "links have discernible text"

### ISSUE THREAD

**Issue by WW3** [dequelabs/axe-core#286] opened 2017-02-22 15:39 UTC
axe does not recognize svg title node as legit accName

**Comment by marcysutton** [comment] 2017-02-22 16:06
Title wasn't always exposed without `aria-labelledby`. @dylanb do you know if that was holding up support axe-core? I know that Chrome in particular has since fixed that discrepancy.

**Comment by dylanb** [comment] 2017-02-22 21:23
I believe we will need to include svg elements in the selector for the image-alt rule and also have logic in the accessible name calculation code in order to fix this

**Comment by dylanb** [comment] 2017-02-22 21:27
This is a duplicate of https://github.com/dequelabs/axe-core/issues/20

**Closed by dylanb** 2017-02-22 21:27 UTC
