### ISSUE TITLE
Div disallowed as immediate child of <dl>

### ISSUE THREAD

**Issue by studiobl** [dequelabs/axe-core#1201] opened 2018-10-24 14:46 UTC
The w3 HTML5 spec allows a div to be the immediate child of a dl, then a dd or dt to be a child of that div, but the Attest Chrome browser extension calls out an error: "<dl> elements must only directly contain properly-ordered <dt> and <dd> groups, <script> or <template> elements"

https://www.w3.org/TR/html5/grouping-content.html#the-dl-element

Here's the list that Attest called out:

```
<dl data-qa-id="account-summary">
    <div class="_3S--zFMxqz" data-qa-id="definition-item-account-summary-0">
        <dt class="_1kW0j6OaMX">Name</dt>
        <dd class="DyjTKZHqTQ">Ms Joanna Smith, Dr.</dd>
    </div>
    <div class="_3S--zFMxqz" data-qa-id="definition-item-account-summary-1">
        <dt class="_1kW0j6OaMX">Account ID</dt>
        <dd class="DyjTKZHqTQ">00000012345</dd>
    </div>
    <div class="_3S--zFMxqz" data-qa-id="definition-item-account-summary-2">
        <dt class="_1kW0j6OaMX">Broken promises to pay - current year</dt>
        <dd class="DyjTKZHqTQ">0</dd>
    </div>
    <div class="_3S--zFMxqz" data-qa-id="definition-item-account-summary-3">
        <dt class="_1kW0j6OaMX">Broken promises to pay - previous year</dt>
        <dd class="DyjTKZHqTQ">2</dd>
    </div>
    <div class="_3S--zFMxqz" data-qa-id="definition-item-account-summary-4">
        <dt class="_1kW0j6OaMX">Next payment due</dt>
        <dd class="DyjTKZHqTQ">05/08/2017</dd>
    </div>
</dl>
```

**Comment by marcysutton** [comment] 2018-10-24 15:34
Thanks for your issue. This should already be handled by the code in https://github.com/dequelabs/axe-core/pull/1076, I think it just needs to be released. Going to close as a duplicate of #262.

**Closed by marcysutton** 2018-10-24 15:34 UTC
