### ISSUE TITLE
Runtime issue: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by ilaneden** [dequelabs/axe-core#2984] opened 2021-06-10 06:55 UTC
<< Please describe how you encountered this issue >>

Trying to run axe on my web-app 
axe-core version: `4.2.0`
axe-extension version: `4.9.3`

```
TypeError: Cannot read property 'data' of undefined
    at Xl._l [as after] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:289593)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324563
    at Array.forEach (<anonymous>)
    at ec.after (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324396)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332384
    at Array.map (<anonymous>)
    at e.value (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332240)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:341091
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:97118
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:100990
```

**Comment by WilcoFiers** [comment] 2021-06-10 12:13
Thank you for reporting. This bug was fixed in axe-core 4.2.2. It is caused by a page having iframes without headings. The fix should be available in the extension soon.

**Closed by WilcoFiers** 2021-06-10 12:13 UTC
