### ISSUE TITLE
Keeps asking to upgrade to AXE pro

### ISSUE THREAD

**Issue by jarrodek** [dequelabs/axe-core#1959] opened 2019-12-20 19:03 UTC
Even though I have signed up and have pro account after a while it asks me again to upgrade to pro again. Clicking on any link only takes me to the registration page. No link to login page. I have to enter the address manually (remembered it accidentally).

Also, please consider extending session timeout on your page (because apparently the extension checks if there's an active session) or even better use other authentication method (OAuth 2 or JWT). This way I won't have to log in each time I want to use the extension.

**Comment by dylanb** [comment] 2019-12-26 16:15
@jarrodek is the extension timeout issue causing performance problems for you? We are trying to track down a problem related to that

**Comment by erik-deque** [comment] 2020-01-03 22:17
@jarrodek we have some work that should address your second issue but we have not been able to reproduce the first one you mentioned. Are there any instructions you can provide that might help us reproduce?

**Comment by jarrodek** [comment] 2020-01-06 20:24
So as the first issue goes, I see this most of the time:
![image](https://user-images.githubusercontent.com/3320020/71846320-22bccd80-307f-11ea-857d-2e6bacb6ae6f.png)

When I press either of both links (below Analyze or top right) I see the registration page that has no option to log in (as I am already registered):
![image](https://user-images.githubusercontent.com/3320020/71846407-55ff5c80-307f-11ea-86a3-9dfa305d4067.png)
Now I don't remember the URL I used to sign in again so I cannot complete the login process.

**Comment by erik-deque** [comment] 2020-01-06 20:49
Do you have cookies disabled or any other extensions that might be affecting storage in some way?

The following link should help you get logged in: https://auth.deque.com/auth/realms/axe/protocol/openid-connect/auth?client_id=axepro-public

**Comment by AutoSponge** [comment] 2020-01-13 14:20
Refreshing, reinstalling, or upgrading(?) the extension will wipe out the data. In phase 2, this will not even be possible. The design should have always pointed at the auth url and offered a link from there to sign up (as it does but maybe more "obvious"?).

**Comment by AutoSponge** [comment] 2020-01-13 14:37
Duplicate of https://github.com/dequelabs/attest-browser-extensions/issues/1520

**Comment by jarrodek** [comment] 2020-01-13 17:21
@erik-deque No cookies processors are installed. Thanks for the link but it also should be somewhere in the registration form as "already registered? Sign in"  :)

**Comment by jarrodek** [comment] 2020-01-13 17:22
@AutoSponge not sure what are you referring to with refreshing/reinstalling/upgrading.
Also referenced link is not public.

**Comment by erik-deque** [comment] 2020-01-15 16:00
A quick update, we have some work in progress that will render this issue moot :)

**Comment by erik-deque** [comment] 2020-05-21 12:10
The sign-in link has been updated to never point at the sign-up page. This has been resolved.

**Closed by erik-deque** 2020-05-21 12:10 UTC
Labels: extension
