### ISSUE TITLE
Item "image-redundant-alt" contains a javascript error and no nodes

### ISSUE THREAD

**Issue by kpeterson85** [dequelabs/axe-core#1704] opened 2019-07-15 21:04 UTC
When running AXE version 3.3.0 against this page (https://www.vizergy.com/hotel-internet-marketing-programs.htm) it is reporting an "image-redundant-alt" item that contains no nodes and has the error "message" value "Cannot read property 'children' of undefined".  The "image-redundant-alt"  item was not present for this same page when running 3.2.0.

To recreate the issue, visit this page in Chrome https://www.vizergy.com/hotel-internet-marketing-programs.htm

Then run the below code within the console which will run AXE 3.3.0 against the page and write out the results object into the console. You can update the CDN path to 3.2.0 to test that version.

<pre><code>
var s = document.createElement("script"); 
s.type = "text/javascript"; 
s.src = "https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js"; 
document.body.appendChild(s); 
setTimeout(function() 
{ 
 axe.run(document, {"reporter": "V2"}, 
  function(error, results) 
  { 
   console.log(results); 
   window.axeresults = results;							 
  } ); 
}, 1000);
</code></pre>

You will then see within the "incomplete" list the "image-redundant-alt" item in the attached screenshot.

![2019-07-15 16_56_11-Window](https://user-images.githubusercontent.com/105022/61248776-c60cd580-a721-11e9-95f7-17fc9d6f84d8.png)

Below is a copy of the full item:

<pre><code>
{
  "id": "image-redundant-alt",
  "impact": null,
  "description": "Ensure image alternative is not repeated as text",
  "message": "Cannot read property 'children' of undefined",
  "stack": "TypeError: Cannot read property 'children' of undefined\n    at Object.g.visibleVirtual (https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:340799)\n    at Object.evaluate (https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:250805)\n    at i.run (https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:58970)\n    at https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:60798\n    at https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:116274\n    at Object.defer (https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:116308)\n    at https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:60776\n    at Array.forEach (<anonymous>)\n    at h.runChecks (https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:60686)\n    at https://cdnjs.cloudflare.com/ajax/libs/axe-core/3.3.0/axe.min.js:12:61700",
  "error": {
    "errorNode": {
      "selector": [
        "img[alt=\"Local\\ Search\\ Optimization\"]"
      ],
      "source": "&lt;img alt=\"Local Search Optimization\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\" data-originalsrc=\"/files/3564/seo-local.png\" class=\"img-responsive media-object\">",
      "xpath": [
        "/div[@id='vizcom-featurelistWidget382043']/div/div/div[2]/div/img"
      ]
    }
  },
  "errorNode": {
    "selector": [
      "img[alt=\"Local\\ Search\\ Optimization\"]"
    ],
    "source": "&lt;img alt=\"Local Search Optimization\" src=\"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\" data-originalsrc=\"/files/3564/seo-local.png\" class=\"img-responsive media-object\">",
    "xpath": [
      "/div[@id='vizcom-featurelistWidget382043']/div/div/div[2]/div/img"
    ]
  },
  "tags": [
    "cat.text-alternatives",
    "best-practice"
  ],
  "help": "Alternative text of images should not be repeated as text",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.3/image-redundant-alt?application=axeAPI",
  "nodes": []
}
</code></pre>

**Comment by straker** [comment] 2019-07-16 20:01
Thanks for reporting the bug. Fix is in a PR.

**Comment by kpeterson85** [comment] 2019-07-17 17:30
@straker Thank you! What would be a good expectation for when the fix would be available in a release?

**Comment by straker** [comment] 2019-07-17 17:46
Once the PR is merged, it will be available in axe-coconut the following day. We'll try to get a release of axe-core itself out sometime after that.

**Comment by jeankaplansky** [comment] 2019-07-19 01:32
No product docs required.

**Comment by chandana7393** [comment] 2019-07-31 09:08
Tested, able to see the error.
![image_redundant_alt](https://user-images.githubusercontent.com/45285854/62199050-70caf800-b3a0-11e9-9e89-696560deeaa3.PNG)
**Tested Environment:**
Axe-coconut - 3.8.1.19721v
Chrome - 76.0.3809.87v
OS - Windows 10 64 bit

**Comment by straker** [comment] 2019-07-31 16:37
@chandana7393 should be fixed in axe 3.3.1 (you're testing with 3.3.0)

**Comment by chandana7393** [comment] 2019-08-01 05:49
@straker 
Tested with axe 3.3.1v, it is still reproducing. Can you please check it.
**Tested Environment:**
Axe-coconut - 3.8.1.21104v
Chrome - 76.0.3809.87v
OS - Windows 10 64 bit.

**Comment by straker** [comment] 2019-08-06 20:00
@chandana7393 It works for me using axe 3.3.1.

![image](https://user-images.githubusercontent.com/2433219/62573074-69996380-b852-11e9-95eb-624ce5672a0f.png)

**Comment by chandana7393** [comment] 2019-08-07 07:48
Tested, working as expected.
![attest_img_alt_issue](https://user-images.githubusercontent.com/45285854/62604359-88146300-b915-11e9-9f44-260b1eac7025.PNG)
**Tested Environment:**
Attest - 2.5.1.19916v
Axe - 2.5.1.19916v
Axe-coconut - 2.5.1.19916v
Chrome -  76.0.3809.87v
Firefox - 68.0.1v
OS - Windows 10 64 bit.

**Closed by chandana7393** 2019-08-07 07:48 UTC
Labels: bug, rules
