### ISSUE TITLE
Seeing errors when scanning an area with the aXe Chrome Extension

### ISSUE THREAD

**Issue by dylanhochreiter** [dequelabs/axe-core#3405] opened 2022-03-04 23:26 UTC
Hello there,

We have seen two intermittent issues scanning an area on one of our applications pages.

One of the errors is the following:
```
TypeError: Cannot read properties of undefined (reading 'getRootNode')
    at axe.js:12:113239
    at Array.find (<anonymous>)
    at ka (axe.js:12:113204)
    at Array.sort (<anonymous>)
    at Ca (axe.js:12:112244)
    at Ra (axe.js:12:113984)
    at Ss (axe.js:12:287325)
    at Ps (axe.js:12:287455)
    at qs (axe.js:12:289367)
    at Object.Vs (axe.js:12:291454)

```
And the other can be seen in this screenshot:
![image (15)](https://user-images.githubusercontent.com/6334160/156855275-28e87e6e-26f5-4f09-845f-fba82076c3b4.png)

These issues were both seen in the following versions:
Google Chrome: 98.0.4758.102
aXe Chrome Extension: v4.23.0
axe-core: v4.4.1

Thanks,

Dylan

**Comment by WilcoFiers** [comment] 2022-03-07 10:13
@dylanhochreiter This isn't enough to go off. Can you provide some information on how to reproduce the issue? My guess is that some script in your page is interfering or overriding DOM properties. That's often the cause of an issue like this. I'd need access to the page, or some other page where you're seeing this issue.

**Comment by dylanb** [comment] 2022-06-10 17:28
closing, dormant

**Closed by dylanb** 2022-06-10 17:28 UTC
Labels: info needed
