### ISSUE TITLE
screen is not defined

### ISSUE THREAD

**Issue by alexlrobertson** [dequelabs/axe-core#1404] opened 2019-03-04 20:57 UTC
Expectation: `axe.run` should run without throwing errors

Actual: `axe.run` throws

```
ReferenceError: screen is not defined
      at Object.getEnvironmentData (node_modules/axe-core/axe.js:3694:39)
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:3880:35
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:3656:23
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:3549:11
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:5992:13
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:2637:9
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:5992:13
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:5992:13
      at rule.run.Object.assign.result (node_modules/axe-core/axe.js:2581:9)
      at /Users/arobert3/Sites/verso/node_modules/axe-core/axe.js:3110:14
      at Timeout._onTimeout (node_modules/axe-core/axe.js:5992:13)
```

Motivation: I want to upgrade my version of `axe-core`

<pre><code>
axe-core version: 3.2.0

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 8.13.0
- Platform:  Mac
</code></pre>

**Comment by WilcoFiers** [comment] 2019-03-07 09:27
Thank you for reporting. Looks like the problem is that we're assuming here that window is the global object.

A workaround would be to do the following before running axe. I'll create a fix for this as well.

```js
global.screen = window.screen
```

**Closed** 2019-03-07 18:01 UTC
Labels: bug, core
