### ISSUE TITLE
Runtime issue: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by dylanhochreiter** [dequelabs/axe-core#3024] opened 2021-06-22 14:02 UTC
<< Please describe how you encountered this issue >>

axe-core version: `4.2.0`
axe-extension version: `4.9.3`

```
TypeError: Cannot read property 'data' of undefined
    at Xl._l [as after] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:289593)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324563
    at Array.forEach (<anonymous>)
    at ec.after (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324396)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332384
    at Array.map (<anonymous>)
    at e.value (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332240)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:341091
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:97118
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:100990
```

We are seeing this issue intermittently whenever we run the tool against the page. Sometimes it will run but it shows 0 or a low amount of issues, which I know is not the case given that we had ran the tool against our pages before with larger results returned.
Any idea as to what the cause could be? This wasn't happening in the winter when we were running the tool against the same or similar pages in our site.

Thanks!

**Comment by dylanhochreiter** [comment] 2021-06-22 14:15
To be clear this is with the Chrome extension. Our pages have have iframes within them, not sure if that is related.

**Comment by dylanhochreiter** [comment] 2021-06-23 17:59
I saw in another ticket that an extension update should be available soon to address this issue. Any update on this?

**Comment by straker** [comment] 2021-06-23 20:49
We're working on releasing the update to the extension soon, probably within the next week or two. Going to close this as a duplicate of #2944.

**Closed by straker** 2021-06-23 20:49 UTC
