### ISSUE TITLE
Runtime issue: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by ahmadkadri** [dequelabs/axe-core#3450] opened 2022-05-05 06:23 UTC
<< Please describe how you encountered this issue >>

axe-core version: `4.4.1`
axe-extension version: `4.26.0`

```
TypeError: Cannot read properties of undefined (reading 'source')
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167184
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167154
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167104
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167000
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:166668
    at Array.map (<anonymous>)
```

**Comment by WilcoFiers** [comment] 2022-05-09 15:27
Can you provide some information on how to reproduce the issue?

**Comment by WilcoFiers** [comment] 2022-07-07 09:23
Unfortunately, since we're not able to reproduce the issue, I'm going to close this. We're going to make some changes so that the stack trace becomes more usable. Hopefully that'll help us better track down these problems in the future.

**Closed by WilcoFiers** 2022-07-07 09:23 UTC
Labels: extension
