### ISSUE TITLE
Error: TypeError: j.split is not a function

### ISSUE THREAD

**Issue by richgps** [dequelabs/axe-core#361] opened 2017-06-15 11:54 UTC
Hi, 

I'm running axe-core via axe-webdriver for selenium and it's throwing the error below. Unfortunately the URL is non-public, so not able to share. 

``` 
\node_modules\selenium-webdriver\lib\promise.js:2634
        throw error;
        ^
JavascriptError: TypeError: j.split is not a function
    at WebDriverError (\node_modules\selenium-webdriver\lib\error.js:27:5)
    at JavascriptError (\node_modules\selenium-webdriver\lib\error.js:133:5)
    at Object.throwDecodedError (\node_modules\selenium-webdriver\lib\error.js:489:11)
    at parseHttpResponse (\node_modules\selenium-webdriver\lib\http.js:519:13)
    at doSend.then.response (\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.executeScript()
    at thenableWebDriverProxy.schedule (\node_modules\selenium-webdriver\lib\webdriver.js:816:17)
    at thenableWebDriverProxy.executeScript (\node_modules\selenium-webdriver\lib\webdriver.js:887:16)
    at module.exports (\node_modules\axe-webdriverjs\lib\inject.js:53:4)
    at AxeBuilder.analyze (\node_modules\axe-webdriverjs\lib\index.js:106:2)
    at \testui.js:12:8
    at ManagedPromise.invokeCallback_ (\node_modules\selenium-webdriver\lib\promise.js:1384:14)
    at TaskQueue.execute_ (\node_modules\selenium-webdriver\lib\promise.js:3092:14)
    at TaskQueue.executeNext_ (\node_modules\selenium-webdriver\lib\promise.js:3075:27)
    at asyncRun (\node_modules\selenium-webdriver\lib\promise.js:2935:27)
    at \node_modules\selenium-webdriver\lib\promise.js:676:7
```
Thanks!

**Comment by WilcoFiers** [comment] 2017-06-15 15:22
@richgps Just going by the stack trace, I really can't say much. It looks like axe is failing to inject. My first guess would be that the page isn't loaded properly. I can't find any "j.split" calls in axe-core, axe-webdriverjs or selenium-webdriver. Does that exist in your code base? Can you provide some way to reproduce this?

**Comment by dylanb** [comment] 2017-06-15 15:41
There are 14 occurrences of split being used in the code and none of them runs at inject time. The do get called within various rules through. Normally when an exception happens in a rule, it results in an incomplete for that element and does not cause an exception to be thrown back to the caller.

**Comment by WilcoFiers** [comment] 2017-08-02 12:42
I'm closing this issue, as it doesn't seem related to anything failing in axe-core or axe-webdriverjs.

**Closed by WilcoFiers** 2017-08-02 12:42 UTC
