### ISSUE TITLE
<video> elements must have an audio description track - Make it a suggestion rather than an error

### ISSUE THREAD

**Issue by Stefany93** [dequelabs/axe-core#1870] opened 2019-10-24 13:09 UTC
Expectation:  Suggest an audio description for `video` elements, don't flag them as errors if missing. 
Actual: Flags all videos without audio descriptions 

Motivation: Videos such as "[talking heads", or presentations on a static background  do not need audio descriptions](https://www.w3.org/WAI/WCAG21/Techniques/general/G203), yet Axe spits out an error. 

I have a talking head video on my website, hence no audio description needed. 

Since it is impossible for axe to determine the content of the video, remove the "critical" error. 

<pre><code>
axe-core version:  (axe-core 3.3.2)
axe-webdriver, v4.0.0

Browser and Assistive Technology versions
Google Chrome 

</code></pre>

**Comment by WilcoFiers** [comment] 2019-10-28 17:17
Hey @Stefany93. You're absolutely right, which is why as of axe-core 3.1.0 we made this return incomplete instead of as a failure:
https://github.com/dequelabs/axe-core/pull/1075

If you are indeed seeing this in 3.3.2, can you provide a way for us to reproduce this, because that definitely shouldn't be happening.

**Comment by straker** [comment] 2019-11-12 22:45
Closing. Please reopen if you find this is giving a violation instead of needs review in latest version of axe.

**Closed by straker** 2019-11-12 22:45 UTC
