### ISSUE TITLE
role="status" fails label check

### ISSUE THREAD

**Issue by trav-is** [dequelabs/axe-core#342] opened 2017-06-05 14:54 UTC
When a properly associated label also has role="status" it fails the check (no clue why status is being used but that is another topic)

ex markup from https://www.aircanada.com/us/en/aco/home.html "my bookings" tab active

`<label for="bookings_bookingReference" aria-live="polite" role="status" aria-atomic="true">
<span class="sr-only">BOOKING REFERENCE</span>
</label>
`

**Comment by marcysutton** [comment] 2017-06-05 22:25
I'm guessing aXe would fail the input for not having a label because the `role="status"` is changing the element's role to `status` from `label`, so it thinks there is no longer a match. It is usually a bad idea to overload an element's default role, but in my testing the input label was still announced. I tested Voiceover in Chrome and Safari, NVDA + Firefox and IE, and JAWS and IE.

**Comment by AutoSponge** [comment] 2019-05-13 19:53
If the tested behavior is not standard, we should probably only accept this pattern if the `input` also has `aria-labelledby` pointing to the label to ensure that the overridden role will not be an issue in the future.

**Comment by dylanb** [comment] 2019-06-16 15:05
This one needs accessibility supported testing

**Comment by straker** [comment] 2019-06-24 21:15
Because of the `role=status` on the label, the accessible name for the label is correctly calculated as the empty string `""` as `role=status` elements [derive their accessible name from the author](https://www.w3.org/TR/wai-aria/#status) and not the contents. Thus the check fails because the label has no accessible name. 

Testing in Chrome and Firefox accessibility devtools shows this is the case. Closing as works as intended.

**Closed by straker** 2019-06-24 21:15 UTC
Labels: bug
