### ISSUE TITLE
Running a11y test in Andriod, iPhone Devices with modern browser

### ISSUE THREAD

**Issue by tapanbasak** [dequelabs/axe-core#165] opened 2016-02-10 13:54 UTC
Hi dylanb....facing some issues while running accessibility test in Andriod, iPhone Devices with modern browser.

If I run the test in andriod device with chrome browser, it is throwing below js exception -

> Javascript error: axe is not defined JavaScript stack: ReferenceError: axe is not defined at eval (eval at executeAsyncScript (unknown source), :4:5) at eval (eval at executeAsyncScript (unknown source), :5:7) at eval (eval at executeAsyncScript (unknown source), :5:33) at executeAsyncScript (:321:26) at :337:29 at callFunction (:229:33) at :239:23 at :240:3 at Object.InjectedScript._evaluateOn (:580:39) at Object.InjectedScript._evaluateAndWrap (:539:52) (Session info: webview=30.0.0.0) (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64)

Is there any way I can execute a11y test in android device with modern browser.

Thanks

**Comment by dylanb** [comment] 2016-02-10 15:21
What is your test setup?

**Comment by dylanb** [comment] 2016-02-11 15:21
I am going to close this because it is a duplicate of the issue in axe-webdriverjs https://github.com/dequelabs/axe-webdriverjs/issues/6

**Closed by dylanb** 2016-02-11 15:21 UTC
