### ISSUE TITLE
axe extension in chrome causing disruptive behavior for syntax highlighting with eleventy-plugin-syntaxhighlight

### ISSUE THREAD

**Issue by tannerdolby** [dequelabs/axe-core#2711] opened 2020-12-22 00:21 UTC
Hello dequelabs team! 

This issue is in reference to [Major issue with syntax-highlight plugin for multi-line code blocks](https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/43) within [eleventy-plugin-syntaxhighlight](https://github.com/11ty/11ty-website/).

I wanted to inform you that when I have the chrome extension `axe - Web Accessibility Testing` enabled, it causes disruptive behavior to [eleventy-plugin-syntaxhighlight](https://www.npmjs.com/package/@11ty/eleventy-plugin-syntaxhighlight) for highlighting fenced code blocks with Prism. 

It causes multi-line fenced code blocks to become single line and disregards the `white-space: pre` style in the Prism stylesheet. It looks like its causing `white-space: pre` to be `white-space: nowrap` where everything is in a single line. (Not sure if this is the exact cause but thats what it looks like)

Expectation: Expect the accessibility testing extension not to cause disruptive behavior to the syntax highlighting that is handled by Prism.js within `eleventy-plugin-syntaxhighlight`.

Actual: Having the `axe - Web Accessibility Testing` extension enabled with access to "all sites" causes multi-line code blocks that are highlighted with `eleventy-plugin-syntaxhighlight` to have their styling messed up causing everything to be in a single line ignoring the CSS that should create line breaks.

Screenshot of a multi-line code block that is forced to be single line when the accessibility extension is enabled with "site access: all sites"

<img width="782" alt="Screen Shot 2020-12-21 at 4 15 03 PM" src="https://user-images.githubusercontent.com/48612525/102834039-b8905c00-43a7-11eb-8106-c48160f049a0.png">

Screenshot of axe extension site access details

<img width="681" alt="Screen Shot 2020-12-21 at 4 02 20 PM" src="https://user-images.githubusercontent.com/48612525/102833492-1e7be400-43a6-11eb-9c98-b944db5fd722.png">

Motivation: I want the behavior to be changed so I can continue to use the axe - Web Accessibility Testing extension alongside `eleventy-plugin-syntaxhighlight` without having to configure any non-default behavior.

Currently as a workaround, @5t3ph pointed out that having the extension enabled with `site access: on click` is one way to avoid the issue I've stated above.

<img width="684" alt="Screen Shot 2020-12-21 at 4 09 18 PM" src="https://user-images.githubusercontent.com/48612525/102833830-17a1a100-43a7-11eb-943c-4ae20cd53952.png">

<pre><code>
axe-core version: 4.6.2

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v11.0.0
- Platform:  MacOS
</code></pre>

**Comment by straker** [comment] 2020-12-22 00:39
Thanks for the issue. @scurker This seems to have popped back up again from https://github.com/dequelabs/axe-core/issues/1868

**Comment by tannerdolby** [comment] 2020-12-22 00:40
Your welcome. I only encountered this issue while using Chrome, not sure if its reproduced in other browsers.

**Comment by mgostisha** [comment] 2020-12-23 16:59
> Your welcome. I only encountered this issue while using Chrome, not sure if its reproduced in other browsers.

I reproduced this in Microsoft Edge v87.0.664.55. Not really surprising, but another data point.

**Comment by garretthyder** [comment] 2020-12-30 18:06
I'm also seeing similar on Chrome when browsing datatables.net, I'd originally logged a ticket there before finding the cause was axe.
https://datatables.net/forums/discussion/comment/184320

**Comment by dzwarg** [comment] 2021-01-07 17:03
This is also disrupting syntax highlighting by highlightjs. See the "HTML" pane at the bottom of page content here:

https://patterns.boston.gov/components/detail/brc.html

**Comment by darekkay** [comment] 2021-01-09 17:21
Same issue as in #2686

**Comment by scurker** [comment] 2021-01-15 18:51
Closing this issue in favor of #2686. Please continue discussion there.

**Closed by scurker** 2021-01-15 18:51 UTC
Labels: extension
