### ISSUE TITLE
Aria listbox and list roles should be allowed to be empty

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#383] opened 2017-06-28 19:10 UTC
This example page shows multiple listboxes, some of which are empty https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox.html

These empty listbox elements should not fail the required children rule. We should create a new category of required children that equates to "required if not empty" and put the `listbox` and `list` roles into this category

**Comment by marcysutton** [comment] 2018-05-16 20:16
The URL above is throwing a 404, as an FYI. This is also relevant to #874.

**Comment by dylanb** [comment] 2018-05-17 12:35
https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-rearrangeable.html

**Comment by jkodu** [comment] 2018-09-12 12:45
@dylanb @WilcoFiers 

As per the fix that was merged for the related issue, https://github.com/dequelabs/axe-core/issues/874, empty listbox elements are flagged as incomplete rather than violation.

Does that suffice for this issue?

**Comment by dylanb** [comment] 2018-09-24 20:18
I think it is wrong to flag them as incomplete but I think that is a debate for a different forum

**Comment by BrendanMcK** [comment] 2018-12-12 06:35
Looks like the fix for #874 allows `listbox` items to be empty, but not `list` items. [code](https://github.com/dequelabs/axe-core/pull/927/files#diff-9b42f0948ee7ca9d3175ad9821a85847R5)

**Comment by chandana7393** [comment] 2019-05-31 09:40
Issues related to "Ensures elements with an ARIA role that require child roles contain them" are displaying under Needs Review.
![list_listitem_needs_review](https://user-images.githubusercontent.com/45285854/58696939-4071d800-83b6-11e9-9e8b-6c077653aa87.PNG)
**Tested Environment:**
Axe-coconut - 3.8.0.15004v
Chrome - 74v
OS - Windows 10 64 bit.

**Comment by padmavemulapati** [comment] 2019-06-03 07:17
@scurker , can you please take look at the comment @chandana7393 kept, if that is the expected behavior, we are good to close the issue.

**Comment by scurker** [comment] 2019-06-03 13:48
Per https://github.com/dequelabs/axe-core/issues/1444#issuecomment-488253893 this is correct behavior. Only the following roles should fail if empty:

* menu
* menubar
* row

**Comment by padmavemulapati** [comment] 2019-06-03 14:24
Thank you @scurker for clarifying this, so we are good to close this tickets as it is giving expected results.

**Closed by padmavemulapati** 2019-06-03 14:24 UTC
Labels: bug, rules
