### ISSUE TITLE
Runtime issue: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by gchis66** [dequelabs/axe-core#3414] opened 2022-03-17 20:29 UTC
Decided to run the devtool extension on a specific div of a website and ran into this issue. Not sure what to make of it

axe-core version: `4.4.1`
axe-extension version: `4.24.4`

```
TypeError: Cannot read properties of undefined (reading 'source')
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167184
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167154
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167104
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167000
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:166668
    at Array.map (<anonymous>)
```

**Comment by gchis66** [comment] 2022-04-18 15:57
Hi I m unable to link the specific website as it is only available on our company staging network. Anything in particular I should consider/look for? Does the axedeque extension run properly on react based websites?

**Comment by straker** [comment] 2022-04-18 17:03
Normally yes, the extension can run properly on any site / framework. The problem is going to be that without being able to see and debug the problem I'm not sure there's much we can do. If you could manage to isolate the problem and post it as a public page somewhere, that'd be the most helpful.

**Comment by WilcoFiers** [comment] 2022-07-07 09:26
Lacking any further information, I don't think we can address this. We're going to make some changes that'll let us better track down problems like this in the future. For now I'm going to close this.

**Closed by WilcoFiers** 2022-07-07 09:26 UTC
Labels: info needed, extension

**Comment by gchis66** [comment] 2022-10-11 08:59
Thanks for your reply. The website in question is only viewable on our
network as it's a staging link for testing before content gets published on
the live website.
