### ISSUE TITLE
Background videos: false positive for videos needing caption tracks

### ISSUE THREAD

**Issue by mfairchild365** [dequelabs/axe-core#249] opened 2016-11-02 20:11 UTC
Background videos (videos that are played in the background with no audio, usually with other content over it) are becomming more and more common. They also pose a problem for accessibility. For a reference on the issue see this great article: http://www.punkchip.com/accessible-html-video-as-a-background/

Right now axe will flag these videos as missing a captions track and description track.

I'm trying to think of some ways to improve that check. I've thought of the following:

1) check if the video is marked up as an image (`role=img`). See my thoughts at: https://gist.github.com/mfairchild365/2dbffbcac3286413c0509ea8e8e7ad7c However, this isn't a standard (and maybe not even the best way) to mark up these kinds of videos.
2) check for the presence of an audio track. Something along the lines of http://stackoverflow.com/questions/21270048/html5-video-how-to-detect-when-there-is-no-audio-track#answer-31022391 However, how would you account for background videos that have an audio track but it is just muted? Check for both of those conditions?

**Comment by WilcoFiers** [comment] 2016-11-07 07:51
I like the idea of checking for the audio. I'm not too sure about the role=img though. That's not a common design pattern as far as I know, so I would say the chance of someone using that the way you intend it isn't likely, unless they are specifically trying to pass axe.

**Comment by marcysutton** [comment] 2017-04-10 20:53
I think our Needs Review workflow will make this better, since the user will get a chance to review it and decide if it's a violation. Therefore I'm going to close this as a duplicate of #285

**Closed by marcysutton** 2017-04-10 20:53 UTC
Labels: question
