### ISSUE TITLE
v4.7.1 broke node <= 6

### ISSUE THREAD

**Issue by ljharb** [dequelabs/axe-core#4127] opened 2023-08-11 19:48 UTC
### Product

axe-core

### Product Version

v4.7.1

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Be requireable in node < 6.

#### Actual
Crashes, because `Object.values` was added in node 7.

#### How to Reproduce
Run `require('axe-core')` in node 6.

#### Additional context
I suggest using https://npmjs.com/object.values until you're ready to release a major version that drops support for node 4-6 (please fix v4 for node <= 6 before doing that). I'd be happy to submit a PR.

**Comment by straker** [comment] 2023-08-14 13:12
Thanks for the issue. Looks like the problem is in [colorjs.io](https://www.npmjs.com/package/colorjs.io) which we brought in to fix https://github.com/dequelabs/axe-core/issues/4007.

**Comment by ljharb** [comment] 2023-08-14 14:58
I’m confused why it would have ended up bundled into the required entrypoint node if it’s a separate package.

**Comment by ljharb** [comment] 2023-09-07 20:43
Looks like v4.8.0 also broke node < 16 by using `Object.hasOwn` somewhere.

**Comment by straker** [comment] 2023-09-07 21:10
@ljharb Thanks for pointing that out. Looks like that was our fault and added in https://github.com/dequelabs/axe-core/pull/4060

**Comment by ljharb** [comment] 2023-09-07 21:14
@straker thanks for the pointer; filed #4152 to fix that.

**Comment by straker** [comment] 2023-10-09 14:51
Closed via v4.8.2

**Comment by ljharb** [comment] 2023-10-09 17:58
@straker i don't think this was fully fixed, since colorjs.io hasn't been updated to have a polyfill yet. https://github.com/dequelabs/axe-core/issues/4127#issuecomment-1710748305 was a separate but related issue.

**Comment by straker** [comment] 2023-10-19 22:19
Yep sorry, I closed because we fixed the `Object.hasOwn` problem and forgot this was talking about `Object.values`. We should probably bring in an `Object.values` polyfill to fix the color.js issue.

**Comment by ljharb** [comment] 2023-10-19 22:23
Unfortunately if it's bundled inside color.js, i think it might need to be fixed there, but I haven't had a chance to dig into it yet.

**Closed** 2023-12-15 16:51 UTC
Labels: fix
