### ISSUE TITLE
Seems Axe is looking for listbox to be an actual child of the combobox node?

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#297] opened 2017-03-27 02:55 UTC
Axe threw an error for the following code and it seems OK. Could it be that the tool is looking for the `role=listbox` to be an actual child of the node that has a `role=combobox`? If so I'd say it should not require it to be a child of the node, as per the example in wai-aria 1.1  which is not a child.
https://www.w3.org/TR/wai-aria-1.1/#combobox

```
<div data-region-name="search" data-item-id="338f5520-f43e-44a7-afb1-c8fa928b399a" data-aura-rendered-by="405:0"><div class="ui-widget" data-item-id="07ec5626-5025-4110-a98a-d015a918875f" data-aura-rendered-by="402:0"><div class="big-search-container selfServiceSearchWrapper forceCommunityOmniBox focused show-result" data-aura-rendered-by="338:0" data-aura-class="selfServiceSearchWrapper forceCommunityOmniBox"><div class="image-wrapper" data-aura-rendered-by="340:0"><div class="no-assigned-image" data-aura-rendered-by="302:0"><div class="default-bg-overlay" data-aura-rendered-by="303:0"></div></div></div><div class="body-search" data-aura-rendered-by="344:0"><form class="search-wrapper has-input" type="search" data-aura-rendered-by="345:0"><div class="search-container" data-aura-rendered-by="346:0"><span class="search-input-group" data-aura-rendered-by="347:0"><span class="search-field-group" data-aura-rendered-by="348:0"><label class="uiLabel" for="356:0" data-aura-rendered-by="351:0" data-aura-class="uiLabel"><span class="assistiveText" data-aura-rendered-by="352:0">Search for product information, product accessories, orders or cases.</span><!--render facet: 354:0--><!--render facet: 355:0--></label><input class="search-field input uiInput uiInputTextForAutocomplete uiInput--default uiInput--input" role="combobox" id="356:0" aria-expanded="true" aria-autocomplete="list" type="text" aria-describedby="" aria-haspopup="listbox" placeholder="Search for product information, product accessories, orders or cases." aria-activedescendant="12:c" data-aura-rendered-by="360:0" data-aura-class="uiInput uiInputTextForAutocomplete uiInput--default uiInput--input" data-interactive-lib-uid="2"><!--render facet: 361:0--><!--render facet: 364:0--></span><button class="slds-button slds-button--neutral search-button uiButton" aria-live="off" type="button" data-aura-rendered-by="378:0" data-aura-class="uiButton"><!--render facet: 379:0--><span class=" label bBody truncate" dir="ltr" data-aura-rendered-by="381:0">Search</span><span class="slds-icon_container slds-icon-utility-search search-button-icon slds-button__icon forceIcon" data-aura-rendered-by="370:0" data-aura-class="forceIcon"><span data-aura-rendered-by="373:0"><svg class="slds-icon--xx-small slds-icon" focusable="false" data-key="search" aria-hidden="true">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/img/slds-icons/v7.6.0/utility-sprite/svg/symbols.svg#search"></use>
</svg></span><span class="slds-assistive-text" data-aura-rendered-by="375:0">Search</span></span></button><button class="slds-button slds-button--neutral close-button uiButton" aria-live="off" type="button" data-aura-rendered-by="387:0" data-aura-class="uiButton"><!--render facet: 388:0--><span class=" label bBody truncate" dir="ltr" data-aura-rendered-by="390:0">Close</span><!--render facet: 392:0--></button></span><div class="result-container" data-aura-rendered-by="395:0"><!--render facet: 306:0--><div data-aura-rendered-by="504:0" class="forceCommunityDeflection" data-aura-class="forceCommunityDeflection"><div class="lookup__menu uiAbstractList uiAutocompleteList" role="listbox" data-aura-rendered-by="536:0" data-aura-class="uiAbstractList uiAutocompleteList"><!--render facet: 531:0--><div class="listContent" data-aura-rendered-by="538:0"><ul class="lookup__list  visible" role="presentation" data-aura-rendered-by="533:0"><li class="lookup__item all suggestion force default uiAutocompleteOption forceCommunityDeflectionOption" role="presentation" data-aura-rendered-by="98:587;a" data-aura-class="uiAutocompleteOption forceCommunityDeflectionOption" data-interactive-uid="3"><a class="all suggestion force" role="option" id="14:c" href="javascript:void(0);" data-aura-rendered-by="99:587;a" tabindex="-1"><span class="type-indicator" data-aura-rendered-by="3:587;a"><span class="slds-icon_container slds-icon-utility-search search-icon slds-button__icon forceIcon" data-aura-rendered-by="8:587;a" data-aura-class="forceIcon"><span data-aura-rendered-by="11:587;a"><svg class="slds-icon--xx-small slds-icon" focusable="false" data-key="search" aria-hidden="true">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/img/slds-icons/v7.6.0/utility-sprite/svg/symbols.svg#search"></use>
</svg></span><span class="slds-assistive-text" data-aura-rendered-by="13:587;a">Search</span></span></span><div class="option-text slds-truncate" data-aura-rendered-by="17:587;a"><span class="all suggestion force suggestionText searchOption uiOutputText" data-aura-rendered-by="20:587;a" data-aura-class="uiOutputText">"wing" in Ascensia Diabetes Community</span><!--render facet: 96:587;a--></div></a></li></ul><div class="emptyListContent" data-aura-rendered-by="540:0"><div class="empty-result" data-aura-rendered-by="510:0"><span class="slds-icon_container slds-icon-utility-search empty-state-icon slds-button__icon forceIcon" data-aura-rendered-by="515:0" data-aura-class="forceIcon"><span data-aura-rendered-by="518:0"><svg class="slds-icon--xx-small slds-icon" focusable="false" data-key="search" aria-hidden="true">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/img/slds-icons/v7.6.0/utility-sprite/svg/symbols.svg#search"></use>
</svg></span><!--render facet: 519:0--></span><span class="empty-state-panel-label" data-aura-rendered-by="520:0">Search for product information, product accessories, orders or cases.</span></div></div><div class="loadingIndicator" data-aura-rendered-by="542:0"><div class="loadingCon siteforceLoadingBalls" data-aura-rendered-by="524:0" data-aura-class="siteforceLoadingBalls"><span class="loadingBall first" data-aura-rendered-by="525:0"></span><span class="loadingBall second" data-aura-rendered-by="526:0"></span><span class="loadingBall third" data-aura-rendered-by="527:0"></span><span class="assistiveText" data-aura-rendered-by="528:0">Loading</span></div></div></div><!--render facet: 532:0--></div></div><!--render facet: 321:0--></div><div class="zero-state-panel" data-aura-rendered-by="397:0"><span class="slds-icon_container slds-icon-utility-search zero-state-icon slds-button__icon forceIcon" data-aura-rendered-by="328:0" data-aura-class="forceIcon"><span data-aura-rendered-by="331:0"><svg class="slds-icon--xx-small slds-icon" focusable="false" data-key="search" aria-hidden="true">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/img/slds-icons/v7.6.0/utility-sprite/svg/symbols.svg#search"></use>
</svg></span><!--render facet: 332:0--></span><span class="zero-state-panel-label" data-aura-rendered-by="333:0">Search for product information, product accessories, orders or cases.</span></div></div></form></div><span class="assistiveText" data-aura-rendered-by="399:0">End of Search Dialog</span></div></div></div>
```

**Comment by marcysutton** [comment] 2017-03-27 18:04
Closing as this is a duplicate of #296

**Closed by marcysutton** 2017-03-27 18:04 UTC
